apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mono-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer
