apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mono-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: danacrsuper.azurecr.io/backend:latest
          ports:
            - containerPort: 5003
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  key: db-connection
                  name: backend-secret
      imagePullSecrets:
        - name: acr-secret
