version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0712@Danchiwaz."
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5003:5003"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=mydb;Username=postgres;Password=0712@Danchiwaz.
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4201:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
